### ISSUE TITLE
Installation failed

### ISSUE THREAD

**Issue by rmueck** [YunoHost-Apps/icecoder_ynh#36] opened 2022-11-02 09:18 UTC
### Describe the bug

Installation failed

### Context

- Hardware: VPS
- YunoHost version: 11.0.10.2
- I have access to my server:  Through SSH
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: **no**

### Steps to reproduce
```sh
$ sudo yunohost app install icecoder
Indicate the ID of the Custom Webapp where you want to install this app: icecoder
Indicate the name of the final_path subfolder containing the files accessible from your browser: /www
```
Result: 
Installation failed.

### Expected behavior
Installation should be sucessful and application works.

### Logs
[paste.yunohost.org](https://paste.yunohost.org/raw/ubetekoduj)

**Comment by alexAubin** [comment] 2023-07-30 15:59
Followup PR in https://github.com/YunoHost-Apps/icecoder_ynh/pull/38, but you've misunderstood the install question .. It asks about an existing my_webapp install (cf https://github.com/YunoHost-Apps/my_webapp_ynh )

Closing because the issue is 9 month old and user probably gave up since then ...

**Closed by alexAubin** 2023-07-30 15:59 UTC
